# Generated by Django 5.2.7 on 2025-10-29 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='myapp.piso')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Libre', 'Libre'), ('Ocupada', 'Ocupada')], max_length=10)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='myapp.bloque')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='myapp.dia')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='myapp.sala')),
            ],
            options={
                'unique_together': {('dia', 'sala', 'bloque')},
            },
        ),
    ]
