# Generated by Django 5.2.7 on 2025-11-05 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bloque_dia_piso_sala_disponibilidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('opcion', models.CharField(choices=[('1', 'Opción 1'), ('2', 'Opción 2'), ('3', 'Opción 3')], max_length=1)),
                ('cupos_maximos', models.PositiveIntegerField(default=1)),
                ('cupos_disponibles', models.PositiveIntegerField(editable=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='myapp.publicaciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
        migrations.RemoveField(
            model_name='bloque',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='bloque',
            name='hora_inicio',
        ),
    ]
