# Generated by Django 5.2.7 on 2025-11-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_publicaciones_uniongrupo_delete_publicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='opcion',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='sala',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='myapp.sala'),
            preserve_default=False,
        ),
    ]
