# Generated by Django 5.2.7 on 2025-11-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_publicaciones_opcion_publicaciones_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='contenido',
            field=models.TextField(max_length=250),
        ),
    ]
