# Generated by Django 5.2.7 on 2025-11-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_publicaciones_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='contenido',
            field=models.TextField(max_length=600),
        ),
    ]
